{% set version = "0.7-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmpi
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rmpi_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rmpi/Rmpi_{{ version }}.tar.gz
  sha256: 8591fa9f50de52535a32b36e7ed142c6ca4e03fdfdbef79a1e27a63ed5322eef

build:
  merge_build_host: true  # [win]
  skip: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - openmpi
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - openmpi

test:
  commands:
    - export OMPI_MCA_plm=isolated && export OMPI_MCA_btl_vader_single_copy_mechanism=none && export OMPI_MCA_rmaps_base_oversubscribe=yes && $R -e "library('Rmpi')"           # [not win]
    - "\"%R%\" -e \"library('Rmpi')\""  # [win]

about:
  home: http://fisher.stats.uwo.ca/faculty/yu/Rmpi
  license: GPL-2.0-or-later
  summary: An interface (wrapper) to MPI. It also  provides interactive R manager and worker environment.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
